"""add verification columns to action_results

Revision ID: 4caf6df29fdd
Revises: 4480dda07fba
Create Date: 2026-08-23 01:17:05.427532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4caf6df29fdd'
down_revision: Union[str, Sequence[str], None] = '4480dda07fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_results', sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('action_results', sa.Column('verified_outcome', sa.String(), nullable=True))
    op.add_column('action_results', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('action_results', sa.Column('verification_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_results', 'verification_detail')
    op.drop_column('action_results', 'verified_at')
    op.drop_column('action_results', 'verified_outcome')
    op.drop_column('action_results', 'verified')
    # ### end Alembic commands ###
