"""add last_scored_at to revenue_risk_cases

Revision ID: 797783860aa4
Revises: 13988a87f3ce
Create Date: 2026-08-23 02:18:55.081021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797783860aa4'
down_revision: Union[str, Sequence[str], None] = '13988a87f3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue_risk_cases', sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revenue_risk_cases', 'last_scored_at')
    # ### end Alembic commands ###
